language: julia
os:
    - osx
    - linux
julia:
    - 1.0
    - nightly
matrix:
    fast_finish: true
    allow_failures:
        - julia: nightly
notifications:
    email: false
#script:
#    - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
#    - julia -e 'Pkg.clone(pwd()); Pkg.build("ZMQ"); Pkg.build("JuliaWebAPI"); Pkg.test("JuliaWebAPI"; coverage=true)';
after_success:
  - julia -e 'cd(Pkg.dir("JuliaWebAPI")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())';
#  - julia -e 'cd(Pkg.dir("JuliaWebAPI")); Pkg.add("Coverage"); using Coverage; Codecov.submit(Codecov.process_folder())';
